language: rust
sudo: required
dist: trusty
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
addons:
    apt:
        packages:
            - libssl-dev
if: branch = master OR type = pull_request
rust:
  - stable
  - beta
  - nightly
# matrix:
  # allow_failures:
    # - rust: nightly

before_cache:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
      cargo install cargo-update || echo "cargo-update already installed"
      cargo install cargo-tarpaulin || echo "cargo-tarpaulin already installed"
      cargo install-update -a
    fi
  - rm -rf /home/travis/.cargo/registry

before_script:
  - cargo install --force cargo-audit
  - cargo generate-lockfile

script:
- cargo clean
- |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
        cargo build --features=stream
        cargo test --features=stream
    else
        cargo build
        cargo test
    fi
- cargo audit

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
     cargo tarpaulin --out Xml
     bash <(curl -s https://codecov.io/bash)
  fi
