[package]
name = "brontide"
version = "0.0.0"
authors = ["kilpatty <seanpkilgarriff@gmail.com>"]
description = "A rust implementation of Handshake and Lightning Network's secure messaging protocol - based on Noise"
license = "MIT"
edition = "2018"

[dependencies]
